<?php
/**
 * @file 
 * Autoheight for the meeting display page.
 */
function aps_autoheight_node_view($node, $view_mode, $langcode) {
	$date_format = FALSE;
	if (menu_get_object() == $node && $node->type == 'screen') {
		drupal_add_js(drupal_get_path('module', 'aps_autoheight') . '/aps_autoheight.js', array('scope' => 'footer'));
		$date_format = TRUE;
	}
	if (menu_get_object() == $node && $node->type == 'room') {
		drupal_add_js(drupal_get_path('module', 'aps_autoheight') . '/aps_autoheight.js', array('scope' => 'footer'));
		$date_format = TRUE;
	}
	if (menu_get_object() == $node && $node->type == 'event') {
		$date_format = TRUE;
	}
	if ($date_format) {
		drupal_add_js(drupal_get_path('module', 'aps_autoheight') . '/aps_dateformat.js', array('scope' => 'footer'));
	}
}

function aps_autoheight_views_pre_render(&$view) {
  switch ($view->name) {
    case 'cluster_display': {
    	drupal_add_js(drupal_get_path('module', 'aps_autoheight') . '/aps_autoheight.js', array('scope' => 'footer'));
    	drupal_add_js(drupal_get_path('module', 'aps_autoheight') . '/aps_dateformat.js', array('scope' => 'footer'));
    	break;
    }
    default:
      break;
  }
}