<?php
/**
 * @file 
 * Autoheight for the meeting display page.
 */
function aps_autoheight_theme_registry_alter(&$theme_registry) {
	if (array_key_exists('date_all_day_label', $theme_registry)) {
		$theme_registry['date_all_day_label']['function'] = 'aps_autoheight_date_all_day_label';
	}
}

/**
 * Theme the way an 'all day' label will look.
 */
function aps_autoheight_date_all_day_label() {
  return t('All day', array(), array('context' => 'datetime'));
}