<?php
/**
 * @file 
 * Autoheight for the meeting display page.
 */
function aps_autoheight_theme_registry_alter(&$theme_registry) {
	if (array_key_exists('date_all_day_label', $theme_registry)) {
		$theme_registry['date_all_day_label']['function'] = 'aps_autoheight_date_all_day_label';
	}
	if (array_key_exists('date_display_range', $theme_registry)) {
		$theme_registry['date_display_range']['function'] = 'aps_autoheight_date_display_range';
	}
}

/**
 * Theme the way an 'all day' label will look.
 */
function aps_autoheight_date_all_day_label() {
  return t('All day', array(), array('context' => 'datetime'));
}

/**
 * Returns HTML for a date element formatted as a range.
 */
function aps_autoheight_date_display_range($variables) {
  $date1 = $variables['date1'];
  $date2 = $variables['date2'];
  $timezone = $variables['timezone'];
  $attributes_start = $variables['attributes_start'];
  $attributes_end = $variables['attributes_end'];

  $start_date = '<span class="date-display-start"' . drupal_attributes($attributes_start) . '>' . $date1 . '</span>';
  $end_date = '<span class="date-display-end"' . drupal_attributes($attributes_end) . '>' . $date2 . $timezone . '</span>';

  // If microdata attributes for the start date property have been passed in,
  // add the microdata in meta tags.
  if (!empty($variables['add_microdata'])) {
    $start_date .= '<meta' . drupal_attributes($variables['microdata']['value']['#attributes']) . '/>';
    $end_date .= '<meta' . drupal_attributes($variables['microdata']['value2']['#attributes']) . '/>';
  }

  // Wrap the result with the attributes.
  return t('!start-date - !end-date', array(
    '!start-date' => $start_date,
    '!end-date' => $end_date,
  ));
}